#!/bin/bash

TMUX_S=$(tmux display-message -p "#S")
if test "$TMUX_S" != "0"; then
    DAEMONIZE="--daemon=$TMUX_S";
    SOCKET="--socket=$TMUX_S";
else
    DAEMONIZE="--daemon";
fi;
if [[ $(ps aux | grep "emacs.*$DAEMONIZE" | wc -l) == 1 ]]; then
# if ! pgrep "emacs $DAEMONIZE" > /dev/null; then
    echo "No emacs daemon running ($TMUX_S)"
    exit 1;
fi;
emacsclient "$SOCKET" -n "$@"
