# -*- mode: shell-script; -*-

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if which fish > /dev/null
then
    exec fish
fi

BASHRCD="${HOME}/.bashrc.d"

if test -d "$BASHRCD"; then
    for FILE in $BASHRCD/*.sh; do
        source "$FILE"
    done
fi

unset BASHRCD

export COLORTERM=truecolor

