# -*- mode: shell-script; -*-

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

{{- if .work_profile }}
{{- if eq .shell "fish" }}
# Dealing with the unability to run chsh
FISH="${FISH:-1}"
if test $FISH -eq 1 && which fish > /dev/null
then
    exec fish
fi
{{- end }}
{{- end }}

BASHRCD="${HOME}/.config/bash"

if test -d "$BASHRCD"; then
    for FILE in $BASHRCD/*.sh; do
        source "$FILE"
    done
fi

unset BASHRCD

export COLORTERM=truecolor

